### ISSUE TITLE
Problems with StaticPaths

### ISSUE THREAD

**Issue by ramirosacruz** [47ng/nuqs#221]
When you use getStaticPath in a dynamic route and you go from one to another (for example I have "/ c / [slug] /" and I go from (path1) `"/c/1/"` to (path2) `"/c/2" `) and you use some "set" (for example "quantity"), the asPath of the first render is memorized (in the example it would be (path1). My solution was to stop using the "set" and use
```ts
const changeQuery = (query) => {
const newPathname = stringifyUrl ({url: router.asPath, query: {... router.query, ... query}});
const newAsPath = stringifyUrl ({url: router.asPath, query: {... query}});
router.push (newPathname, newAsPath);
};
```

I'm using
```json
"next": "9.5.3",
"next-usequerystate": "^ 1.3.0",

```
It may be a nextjs bug because if I do this the same thing happens:

```ts
router.query.hello = "2"
router.push (router)
```

**Comment by franky47** [comment]
This sounds like a Next.js bug indeed.

It probably comes from the fact that when touching the URL via the Next.js router, a full page re-render occurs, including the `<App>` component, which runs `getStaticProps` in development.

**Comment by franky47** [comment]
Closing this issue as the internals have changed a lot since the 1.3.0 version. Feel free to reopen if still relevant.
