### ISSUE TITLE
When updating value, remove from URL if new value == defaultValue

### ISSUE THREAD

**Issue by ctian1** [47ng/nuqs#320]
could be done [here](https://github.com/47ng/next-usequerystate/blob/f17d9a24227c2fc36bcd1aa2c3214187a7393432/src/useQueryState.ts#L253)

**Comment by franky47** [comment]
While it would help keeping URLs clean, I don't think it's ultimately a good idea, for the following reason: defaults can change.

Setting the value to `null` is a clear indication that the option is no longer necessary in the URL and should be cleared.

But when setting the state to a particular value, be it the default or not, it should reflect as-is in the URL.

**Comment by tonyxiao** [comment]
Related note, is there an API to clear a query param completely?

**Comment by tonyxiao** [comment]
Nvm found it. Using `null` works. Though it is unexpected that `undefined` would be serialized to string rather than having the same effect as `null`

**Comment by franky47** [comment]
> Nvm found it. Using `null` works. Though it is unexpected that `undefined` would be serialized to string rather than having the same effect as `null`

`undefined` should not be a valid type for a string-based query state (`string | null`), do you mind sharing in which context you encountered it?

**Comment by franky47** [comment]
@ctian1 after multiple requests for this feature, there's an initial implementation in #493, using an option to clear the key-value pair when setting the state to the default value.
