### ISSUE TITLE
Updating state with shallow false makes multiple reenders

### ISSUE THREAD

**Issue by juliomuhlbauer** [47ng/nuqs#370]
When changing the search param with shallow: false, makes multiple reenders on client and blocks the RSC to refetch when the client component is heavy.

**Comment by juliomuhlbauer** [comment]
I think that is a Nextjs problem.
I am testing this to give a real reproduction. But I have a reproduction showing some reendes in useSearchParams()

https://search-param-35vu.vercel.app/search-param

https://github.com/juliomuhlbauer/search-param/

Try to click in the links to change the search params. For now the Select does nothing.

I will expand the reproduction to show when the UI is heavy.

**Comment by juliomuhlbauer** [comment]
Now I made an example with the next-usequerystate and it causes multiple reenders.

This example doesn't block the UI. But when it is with heavy UI it blocks.

https://search-param-nqx9ne9vw-juliomuhlbauer.vercel.app/use-query

Check de console

https://github.com/juliomuhlbauer/search-param/

**Comment by juliomuhlbauer** [comment]
Made an directory with a heavy UI. Well is not that heavy, but it blocks the render.

https://search-param-wine.vercel.app/use-query-with-select

**Comment by juliomuhlbauer** [comment]
A workround kind of works: https://search-param-wine.vercel.app/use-query-with-select-in-layout-custom

But is does give an error of React and it does not get the value SSR.

![image](https://github.com/47ng/next-usequerystate/assets/53458125/b6d03e3e-b9f1-42bd-9383-7e567f477cef)

**Comment by franky47** [comment]
Thanks, I was able to reproduce on my end, will take a look.

I found on the playground that there are two renders on the first query update after a hard reload of the page, but only one for subsequent ones, not sure why.

Also, in development React will use strict mode which performs two render passes per actual render to fish out incorrect useEffect usage, so checking for renders should be done in a production build.

**Comment by juliomuhlbauer** [comment]
Try removing the useSearchParam hook. I think Nextjs makes a reender whithin the Suspense boundary and causes the UI to reender multiple times.

I created a alternative hook for useSearchParam, but it only works client side. So need to import dynamically without ssr.

**Comment by juliomuhlbauer** [comment]
Maybe this involves the behavior of useSearchParams: https://nextjs.org/docs/app/api-reference/functions/use-search-params#behavior

I dont't know why its different from the useParams hook.

**Comment by juliomuhlbauer** [comment]
Thanks! I opened an issue to the Ark UI library: https://github.com/chakra-ui/ark/issues/1738

But I think it is a Nextjs bug.

**Comment by juliomuhlbauer** [comment]
I opened an issue on Nextjs: https://github.com/vercel/next.js/issues/58684

**Comment by franky47** [comment]
Closing as unrelated to `nuqs` (behaviour is reproducible without it).
