### ISSUE TITLE
URL state not available via getters

### ISSUE THREAD

**Issue by tordans** [47ng/nuqs#400]
This ticket is now about https://github.com/47ng/next-usequerystate/issues/400#issuecomment-1814303357 by [damian-balas](https://github.com/damian-balas).

(I moved my report to https://github.com/47ng/next-usequerystate/issues/404.)

**Comment by franky47** [comment]
Thanks for the detailed report. I'll have a look later, but at first glance, it looks like your initialisation performs side-effects in the render function, which is not recommended by React.

**Comment by tordans** [comment]
Thanks @franky47. I forgot to add this video to the report which shows the issue in action https://we.tl/t-3JBSbIevOt
(The linked repo has a dependency on a database which makes it hard to setup quickly…)

**Comment by damian-balas** [comment]
@franky47 I've found a weird behavior. I won't go into details until you say it's a real issue.



The case:
1. I update in ComponentA the query with setter from
```ts
const useMenuQueryState = () =>
  useQueryState('menu', parseAsBoolean.withDefault(false));
```
like this: `setIsMenuOpen(true)`
2. In ComponentB I use a hook from next: `useSearchParams`
3. In ComponentB i use this code on button click / interval / useEffect etc.:
```ts
console.log(
  new URLSearchParams(Array.from(searchParams.entries())).toString()
)
```

The logged query doesn't change even though I see the change being applied by your library in the address bar.

**Questions:**
1. Am I doing something wrong?
2. Should I give you more info?
3. Is there a possibility to get all query data with your library that would equal this:
```ts
new URLSearchParams(Array.from(searchParams.entries())).toString(),
```

Thanks!

**Comment by franky47** [comment]
@damian-balas in stock[^1] Next.js, `useSearchParams` is not reactive to shallow URL updates. Since the setters change the URL in a shallow manner by default (ie: without going through the Next.js router to avoid sending network requests), it is not picked up by `useSearchParams`.

[^1]: As of `next@14.0.3-canary.6`, the experimental `windowHistorySupport` flag changes this behaviour and makes `useSearchParams` reactive to shallow URL changes. However, doing so will still lag behind the state update, because of the internal throttling of URL updates. To get an update in the next render (like you would in `useState`), use a query getter: `useMenuQueryState()[0]`

**Comment by damian-balas** [comment]
> @damian-balas in stock[1](#user-content-fn-1-1f35a779825f00a343bfc66e80be204d) Next.js, `useSearchParams` is not reactive to shallow URL updates. Since the setters change the URL in a shallow manner by default (ie: without going through the Next.js router to avoid sending network requests), it is not picked up by `useSearchParams`.
> 
> Edit: if you want to be notified of URL updates, you can use the `subscribeToQueryUpdates` function:
> 
> ```ts
> import { subscribeToQueryUpdates } from 'next-usequerystate'
> 
> React.useLayoutEffect(
>   () => subscribeToQueryUpdates(({ search }) => console.log(search.toString()),
>   []
> )
> ```
> 
> ## Footnotes
> 1. As of `next@14.0.3-canary.6`, the experimental `windowHistorySupport` flag changes this behaviour and makes `useSearchParams` reactive to shallow URL changes. However, doing so will still lag behind the state update, because of the internal throttling of URL updates. To get an update in the next render (like you would in `useState`), use a query getter: `useMenuQueryState()[0]`. [↩](#user-content-fnref-1-1f35a779825f00a343bfc66e80be204d)

Thanks :)
I've implemented "my own" version of `useSearchParams` as an substitute.
This is what I came up with:

```ts
const useSubscribedSearchParams = () => {
  const _searchParams = useSearchParams();
  const [searchParams, setSearchParams] =
    useState<URLSearchParams>(_searchParams);

  useLayoutEffect(
    () =>
      subscribeToQueryUpdates(({ search }) => {
        setSearchParams(search);
      }),
    // * This returns an unsubscribe function
    [],
  );

  return searchParams;
};
```

It works well :)

My last question is... how should I actually handle changing dynamic queries?

Example:
1. Get current search query
2. Add dynamic key that comes via props
3. Update the search query

How would you handle that case? 

Help much appreciated! :)

**Comment by franky47** [comment]
I would use a useQueryState to update the URL, that's what it's intended to do. If the key is not known ahead of time, or there can be an arbitrary number of them, you can use `useQueryStates` to go around the rules of hooks:

```tsx
function DynamicQuery({ keys }: { keys: string[] }) {
  const [values, update] = useQueryStates(
    keys.reduce((obj, key) => ({
      ...obj,
      [key]: parseAsString
    }), {})
  )
```

**Comment by oliverstreissi** [comment]
> I would use a useQueryState to update the URL, that's what it's intended to do. If the key is not known ahead of time, or there can be an arbitrary number of them, you can use `useQueryStates` to go around the rules of hooks:
> 
> ```tsx
> function DynamicQuery({ keys }: { keys: string[] }) {
>   const [values, update] = useQueryStates(
>     // Note: might want to memoize this
>     keys.reduce((obj, key) => ({
>       ...obj,
>       [key]: parseAsString
>     }), {})
>   )
> ```

Thanks for the example, but how can I type this properly, since values in this case is of type {} and using `useQueryState<Record<string, string>>(...)` gives me `Property 'parse' is missing in type 'string' but required in type 'Parser<any>'`

**Comment by franky47** [comment]
@oliverstreissi this should do it (note however that this is a bit of a hack):

```ts
const [values, update] = useQueryStates(
  // Note: might want to memoize this
  keys.reduce(
    (obj, key) => ({
      ...obj,
      [key]: parseAsString
    }),
    {} as Record<string, Parser<string>>
  )
)
```

If using default values, you'll need to be explicit about the default value existing on the `reduce` initial object:
```ts
const [values, update] = useQueryStates(
  // Note: might want to memoize this
  keys.reduce(
    (obj, key) => ({
      ...obj,
      [key]: parseAsString.withDefault('')
    }),
    {} as Record<string, Parser<string> & { defaultValue: string }>
  )
)
```

**Comment by tordans** [comment]
@damian-balas I am under the impression that this is solved so I will close it. I can reopen if needed, of course.
