### ISSUE TITLE
URL query params are not detected when navigating with the Next Link component

### ISSUE THREAD

**Issue by muezz** [47ng/nuqs#416]
## Context

What's your version of `next-usequerystate`?

```
"next-usequerystate": "^1.13.0"
```

Next.js information (obtained by running `next info`):

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.8.1
      npm: 10.1.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.3
    Next.js Config:
      output: N/A
```

Are you using:

- ✅ The app router

## Description

When I navigate using the Next Link component (and there are query/search params in the href), the `useQueryState` does not detect the param.

I have verified by using the `useSearchParams` hook from Nextjs. 

## Reproduction

Please refer to [this](https://codesandbox.io/p/devbox/old-violet-6hr9ks?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpl14vjq00093b6ez8miael0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpl14vjq00023b6ejg39pscv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpl14vjq00063b6e1b17zzwb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpl14vjq00083b6emag3w9lw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpl14vjq00023b6ejg39pscv%2522%253A%257B%2522id%2522%253A%2522clpl14vjq00023b6ejg39pscv%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpl14vjq00083b6emag3w9lw%2522%253A%257B%2522id%2522%253A%2522clpl14vjq00083b6emag3w9lw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpl14vjq00073b6eig3gk9j8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fpage-with-params-usequerystate%253Ftype%253Dsome-type%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpl14vjq00073b6eig3gk9j8%2522%257D%252C%2522clpl14vjq00063b6e1b17zzwb%2522%253A%257B%2522id%2522%253A%2522clpl14vjq00063b6e1b17zzwb%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clpl2nuo500k83b6exezpuifp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpl2nuo500k83b6exezpuifp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A17.734374999999986%257D
) code sandbox.

Example: Steps to reproduce the behavior:

1. Open the Code Sandbox
2. Go to all pages by clicking on the top bar. All page names explain their purpose.
4. Notice how search params are not found when using this package.

**Comment by o-az** [comment]
@franky47 I'm curious if this issue is related to this:

```ts
const [search, setSearch] = useQueryState('query')
```
When I manually set the url to `?query=abc` and log `query` I get `null`. Is this expected behavior?

**Comment by franky47** [comment]
@o-az what do you mean by "manually" ?

As an update on this issue, Next.js 14.0.3 broke a lot of scripts patching the history APIs (including this library). Turning on the experimental `windowHistorySupport` flag helps resolve the issue, and a general fix is coming in https://github.com/vercel/next.js/pull/58861, which should be available in the next few canaries, and should make its way to Next.js 14.0.4.

**Comment by franky47** [comment]
@o-az Thanks for clarifying. Feel free to [open another issue](https://github.com/47ng/next-usequerystate/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) with your exact setup, this will help me understand your issue better and how to address it.

**Comment by franky47** [comment]
Next.js 14.0.4 has just been released, and contains the fix for shallow routing which caused this issue. Solutions are to either update to 14.0.4, or if you're stuck on 14.0.3, use the `windowHistorySupport` experimental flag.
