### ISSUE TITLE
Setting default value again should remove the query param from the url

### ISSUE THREAD

**Issue by oliverstreissi** [47ng/nuqs#488]
## Context

What's your version of `nuqs`?
1.16.1

Are you using:

- ❌ The app router
- ✅ The pages router
- ❌ The `basePath` option in your Next.js config
- ❌ The experimental `windowHistorySupport` flag in your Next.js config

## Description

Setting the default value again should remove the query param the same way as by setting it to null.

## Reproduction

Example: Steps to reproduce the behavior:

1. Create a useQueryState with a default value
2. Update the state with a different value than the default value
3. Set the default value again
4. Query param is still in the url

 -->

**Comment by franky47** [comment]
This was already discussed in https://github.com/47ng/nuqs/issues/320#issuecomment-1398234230.

Now since this seems to be a popular request, maybe an option could be added to enable this behaviour, what do you think?

```ts
const [, setFoo] = useQueryState('foo', {
  defaultValue: '',
  clearWhenSettingDefault: true // proposal
})

setFoo('') // equivalent to setFoo(null)
```

**Comment by oliverstreissi** [comment]
Yes would be totally fine! In my opinion it would make even more sense to turn it on per default, since defaults are not changing that often, I'd say.

**Comment by franky47** [comment]
@oliverstreissi See #493 for an initial implementation.

For backwards-compatibility purposes, the default remains to be explicit about setting the default value in the URL, and clearing it is an opt-in.
