### ISSUE TITLE
Performance issues when updating to nuqs latest version

### ISSUE THREAD

**Issue by ShadiBlitz** [47ng/nuqs#532]
## Context

What's your version of `nuqs`?

```
^1.17.1
```

Next.js information (obtained by running `next info`):

```
next: 14.0.4
```

Are you using:

- ❌ The app router
- ✅ The pages router
- ❌ The `basePath` option in your Next.js config
- ❌ The experimental `windowHistorySupport` flag in your Next.js config

## Description

After updating from `next-usequerystate ^1.10.0` to `nuqs ^1.17.1`, app became very slow (sometime unresponsive), high memory usage, many unnecessary re-renders.
However, once discard the changes and revert to the old version, everything runs smooth, and none of the render issues take place.

**Comment by franky47** [comment]
I would strongly recommend updating Next.js to 14.1.2 or later, as versions in the 14.0.1 to 14.1.1 range had issues with shallow routing, # see the [known issues](https://github.com/47ng/nuqs/issues/423) for more details.

If the problem persists, could you provide a minimal reproduction example please?

**Comment by ShadiBlitz** [comment]
Closing the issue, performance is back as expected with NextJS version 14.2
