### ISSUE TITLE
Demo links in docs are broken

### ISSUE THREAD

**Issue by tuffstuff9** [47ng/nuqs#553]
Hi. The [hex-colors demo](https://github.com/47ng/nuqs/blob/next/packages/docs/src/app/(pages)/playground/hex-colors/page.tsx) and [server-side parsing demo](https://github.com/47ng/nuqs/blob/next/packages/docs/src/app/(pages)/playground/server-side-parsing) links are not working. Not sure if the examples are being refactored or if this was unintentional.

**Comment by franky47** [comment]
If you are talking about the playground pages' "Source on GitHub" links, they all work on my end. Or is it something else?

**Comment by tuffstuff9** [comment]
> If you are talking about the playground pages' "Source on GitHub" links, they all work on my end. Or is it something else?

Sorry I should have clarified. On the github docs page: https://github.com/47ng/nuqs. You can ctrl f and search 'demo' and click on the links.

**Comment by franky47** [comment]
Ah, good catch, thanks!
