### ISSUE TITLE
`useQueryState` returns a different function if the key is changed

### ISSUE THREAD

**Issue by Chasmical** [47ng/nuqs#587]
## Context

What's your version of `nuqs`?

```
    "nuqs": "^1.17.4",
```

Next.js information (obtained by running `next info`):

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16319
  Available CPU cores: 6
Binaries:
  Node: 22.3.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

Are you using:

- ✅ The app router
- ❌ The pages router
- ❌ The `basePath` option in your Next.js config
- ❌ The experimental `windowHistorySupport` flag in your Next.js config

## Description

Right now `useQueryState` returns a different setter function, if the provided key is changed. The example below would only update the value of the `?key=` query parameter, even if you provide a different `queryKey` to the hook.

This issue can be fixed by adding `setQueryState` to the `useEffect`'s dependencies, but I think it would be safer and more convenient if `useQueryState` returned the same function, similar to how many other React state hooks work, like `useState` and `useReducer`.

## Reproduction

1. Go to https://codesandbox.io/p/devbox/nextjs-app-router-forked-f22tpt.
2. Change "query value" to "abc". `?key=abc` is set as expected.
3. Change "query key" to "number", and then "query value" to "0".

4. Expected: `number` parameter would appear in the query: `?key=abc&number=0`.
   Current: `key` parameter is updated instead: `?key=0`.

![image](https://github.com/user-attachments/assets/205bae16-6ea7-4314-bfd6-b7b3f6a5c7ba)

**Comment by franky47** [comment]
I would say this is expected, as the state updater function has a dependency on the key, unlike `useState` which doesn't have external dependency.

**Comment by Chasmical** [comment]
Yeah, I guess you're right. I noticed this only in the development environment with Hot Reload, and it would be quite unusual for a real app to change keys like that.
