### ISSUE TITLE
Does not work with pages only router (next/useRouter)

### ISSUE THREAD

**Issue by jhensley** [47ng/nuqs#591]
## Context

What's your version of `nuqs`?

`"nuqs": "^1.17.4",`

```
-> Paste result from `cat package.json | grep -e nuqs -e next-usequerystate` here
```

Next.js information (obtained by running `next info`):

```
-> Paste result from `next info` here
```

Are you using:

- ❌ The app router
- ✅ The pages router
- ❌ The `basePath` option in your Next.js config
- ❌ The experimental `windowHistorySupport` flag in your Next.js config

## Description

When _exclusively_ using `pages` router, Next throws an error due to AppRouterContext being null. See: https://github.com/vercel/next.js/blob/44bac5100d0ae6afef2925c3d88810c63eaf3eba/packages/next/src/client/components/navigation.ts#L117

## Reproduction
... Will work on it

**Comment by jhensley** [comment]
I've seen other threads referencing an import specific for `pages` routers (i.e. `import { useQueryState } from 'nuqs/pages'`) -- seems like an ideal solution.

**Comment by franky47** [comment]
What's your Next.js version?

**Comment by jhensley** [comment]
> What's your Next.js version?

`14.2.1`

**Comment by franky47** [comment]
I was not able to get this error with a minimal reproduction repo ([source here](https://github.com/franky47/nuqs-repro-591)).

Could there be something else in your application setup causing this error?

**Comment by franky47** [comment]
Going to close this issue, feel free to reopen it with a link to a reproduction repository.
