### ISSUE TITLE
500 error on demo site.

### ISSUE THREAD

**Issue by ariesclark** [47ng/nuqs#603]
https://github.com/user-attachments/assets/772d01d2-efdb-4b27-9269-16fe193df24e

**Comment by franky47** [comment]
Thanks for the report, I was able to reproduce it too.

`nuqs` comes with a thottling mechanism for updating the URL, to circumvent rate-limits set by browsers (which trigger this error).

After trying to tweak those rates, thinking browsers may have updated them (it happened with Safari), I found that I needed to consistently **double** all rates. Looking at the debug logs, this comes from Next.js also [doing history updates on navigation](https://github.com/vercel/next.js/blob/9720d0adc0b0687267e35804b6f6380fa351ab0c/packages/next/src/client/components/app-router.tsx#L101-L103), essentially doubling the number of calls (and so require double the time between them to stay within rate limits).
