### ISSUE TITLE
Don't run `pkg.pr.new` if there aren't changes to the `nuqs` package

### ISSUE THREAD

**Issue by franky47** [47ng/nuqs#655]
[pkg.pr.new](https://pkg.pr.new) is a service by StackBlitz to deploy previews of NPM packages without polluting the NPM registry (it's pretty cool).

At the moment the PR preview workflow ([`pkg.pr.new.yml`](https://github.com/47ng/nuqs/tree/next/.github/workflows/pkg.pr.new.yml)) runs on any PR.

This is kind of wasteful on pkg.pr.new's servers and resources: we should abort if the PR introduces no changes to what's actually being deployed.

PRs welcome!

**Comment by chbg** [comment]
Hi, @franky47 ! I’ve submitted a pull request that addresses this issue by adding a conditional check to pkg.pr.new.yml to prevent unnecessary runs when there are no changes to the nuqs package. You can view the PR [here](https://github.com/47ng/nuqs/pull/656). Looking forward to your feedback!
