### ISSUE TITLE
Nuqs not parsing on pasting the url

### ISSUE THREAD

**Issue by gajraj-gan** [47ng/nuqs#685]
## Context

What's your version of `nuqs`?

```
"nuqs": "^1.17.6",
```

Next.js information (obtained by running `next info`):

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

Are you using:

- ❌ The app router
- ✅ The pages router
- ❌ The `basePath` option in your Next.js config
- ❌ The experimental `windowHistorySupport` flag in your Next.js config

## Description

We are using the useQueryState to parse the state. When I redirect to the page from another page, the library parses it correctly but if I paste the url in a new tab -- the state is not parsed and returns the default value.

E.g.

```
http://localhost:4200/sound-effects?tab=history
```

If I redirect to this page tab="sometingelse" it works, but if I paste the url directly value of tab will not be history

**Comment by franky47** [comment]
Could you show me a minimal reproduction example please?

One caveat with the pages router on initial navigation is that the URL elements (search params included) won't be available on the first render if it's a static page: Next will use an empty set of search params from when the pages was built, hydrate with this empty set (to avoid hydration errors) and then re-render with the available search params.

See #290 for reference and possible actions.

**Comment by franky47** [comment]
Closing this for now, if still relevant please reopen with a reproduction repository.
