### ISSUE TITLE
Error while loading rule 'import/no-cycle': Package subpath './adapters/next/app' is not defined by "exports"

### ISSUE THREAD

**Issue by GBvanDam** [47ng/nuqs#691]
## Context

What's your version of `nuqs`? 

```
"nuqs": "^2.0.0",
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```
"next": "^14.2.15",
```

## Description

eslint fails on `import { NuqsAdapter } from 'nuqs/adapters/next/app'` with message: 

```bash
Error while loading rule 'import/no-cycle': Package subpath './adapters/next/app' is not defined by "exports"
```

## Reproduction

1. `import { NuqsAdapter } from 'nuqs/adapters/next/app'`
2. install `"eslint": "^8.57.0"`
3. install `"eslint-plugin-import": "^2.31.0"`
4. install `"eslint-import-resolver-alias": "^1.1.2"`
5. run eslint

**Comment by franky47** [comment]
Thanks for the report, the bundling looks fine on my end. What's your ESLint version?

Could you paste your tsconfig.json here please?

**Comment by franky47** [comment]
Ah I think I see what the problem might be.

For some TypeScript configs (that didn't support/honor export paths), the import needed to have top-level .d.ts files that point to the correct ones in the `dist` directory.

Looks like the ESLint rule chokes on those files, where: `node_modules/nuqs/adapters/next/app.d.ts` exports everything from `node_modules/nuqs/dist/adapters/next/app.d.ts`.

I'll see in what cases we need those intermediate top-level declaration files. If we could do without, I'd be happy, they are a pain to maintain.

**Comment by acocheo** [comment]
Almost same problem here I think. Same eslint `^8.57.0` but happens also  with `v.^2.0.1` 
```
 Error while loading rule 'import/no-cycle': Package subpath './adapters/next/app' is not defined by "exports" in /[...]/node_modules/nuqs/package.json
 Occurred while linting [...]
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at findModulePath ([...]/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at exports.resolve ([...]/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at withResolver ([...]/node_modules/eslint-module-utils/resolve.js:180:23)
    at fullResolve ([...]/node_modules/eslint-module-utils/resolve.js:201:22)
```
Seems a problem of how node `Module._findPath` works

**Comment by franky47** [comment]
Could you show me your eslint config please? I'm trying to reproduce on a fresh repo.

**Comment by franky47** [comment]
With that config & packages, running `eslint` passes fine on a fresh install, maybe there's something else?

https://github.com/franky47/nuqs-repro-691

**Comment by franky47** [comment]
Ah I see, `pnpm lint` is running `next lint`, I do get the failure with this. I was running `eslint` at the root of the repo (which passes).

**Comment by franky47** [comment]
OK I found the issue: eslint 8 only supports CJS exports in package.json, and nuqs 2 is ESM only.

Adding this in nuqs's `package.json` moves the needle a bit further (even though it's plain wrong):

```
{
  "exports": {
    "./adapters/next/app": {
      "types": "./dist/adapters/next/app.d.ts",
      "import": "./dist/adapters/next/app.js",
      "require": "./dist/adapters/next/app.js" // Line added
    }
  }
}
```

**Comment by acocheo** [comment]
Yes, the fix is correct! (damn, I saw that file but I didn't think about that..)

**Comment by franky47** [comment]
I can't add this as-is to the package.json, as there isn't a valid CJS bundle to point to, and pointing to the ESM one just for ESLint to be happy seems like opening a can of worms.

I just tried replacing them with `"require": null`, which seems more correct, but it also fails.

Looks like updating to ESLint 9 won't help, as the error comes from `eslint-import-resolver-alias` which is a CJS package (and hasn't been updated in 6 years, so unlikely it moves to ESM).

Unfortunately, Node.js 23's CJS/ESM interop doesn't seem to help here either.

So yeah the best course of action would be to do a local patch-package to add this hack (we can add that to the caveats section in the docs, and link back to this issue)

**Comment by franky47** [comment]
One other thing that works: pointing the `"require"` exports to an empty CJS file:

```json
{
  "exports": {
    "./adapters/next/app": {
      "types": "./dist/adapters/next/app.d.ts",
      "import": "./dist/adapters/next/app.js",
      "require": "./dist/empty-file-for-eslint.cjs"
    }
  }
}
```

**Comment by acocheo** [comment]
Uhm, strange. Setting this line
```
"require": "./dist/adapters/next/app.js" // Line added
```
makes eslint to works correctly in my case.
And I use `eslint-import-resolver-alias`

**Comment by franky47** [comment]
Can y'all try this?

```shell
pnpm add https://pkg.pr.new/nuqs@701
```

**Comment by acocheo** [comment]
It works
