### ISSUE TITLE
TypeError: v.toISOString is not a function

### ISSUE THREAD

**Issue by bryanjtc** [47ng/nuqs#692]
## Context

What's your version of `nuqs`?

```
2.0.0
```

What framework are you using?

- ✅ React Router

Which version of your framework are you using?

```
6.27.0
```

## Description

I used the createSerializer utility where a param is using the parseAsIsoDateTime parser and I have this error. The value is an iso 8601 string. I expected it to not throw an error. The temporary fix is to convert the iso 8601 string to a Date object first and then use the value in the serializer.
```js
chunk-FFJRS6S6.js?v=7de39fa0:7581 Uncaught TypeError: v.toISOString is not a function
    at Object.serialize (nuqs.js?v=7de39fa0:209:23)
    at serialize (nuqs.js?v=7de39fa0:314:32)
```
Here is the code that throws the error
```js
var parseAsIsoDateTime = createParser({
  parse: (v) => {
    const date = new Date(v);
    if (Number.isNaN(date.valueOf())) {
      return null;
    }
    return date;
  },
  serialize: (v) => v.toISOString()
});
```

## Reproduction

1. Create a serializer
2. Add a param with the parseAsIsoDateTime parser
3. Add an iso 8601 string value in the serialize function

**Comment by franky47** [comment]
That would work. Do you not have an error when trying to serialize a string though? Because it should only accept a Date object.

> TypeScript should give you an error when trying to pass a string to the serialize function.

**Comment by bryanjtc** [comment]
> That would work. Do you not have an error when trying to serialize a string though? Because it should only accept a Date object.
> 
> > TypeScript should give you an error when trying to pass a string to the serialize function.

No. I converted the string (value) to a Date object first
