### ISSUE TITLE
 Cannot find module next/navigation (nuqs 2.0.0)

### ISSUE THREAD

**Issue by tiagoskaneta** [47ng/nuqs#693]
## Context

What's your version of `nuqs`?

```
"nuqs": "^2.0.0",
```

What framework are you using?

- ✅ Next.js (pages router)

Which version of your framework are you using?

```
next: 15.0.0
```

## Description

Getting the following after installing nuqs@2.0.0 in a next.js 15 project:

```
Error: Cannot find module '/.../my-app/node_modules/next/navigation' imported from /.../my-app/node_modules/nuqs/dist/chunk-YYVIPTKH.js
Did you mean to import next/navigation.js?
```

Also occurs on a project created from scratch.

## Reproduction

1. Create new Next.js (15) project with Pages router
2. Install nuqs@2.0.0
3. Add Pages adapter
4. `npm run dev`

**Comment by franky47** [comment]
Can you try this version and see if it works for you? 
```
pnpm add https://pkg.pr.new/nuqs@694
```

**Comment by tiagoskaneta** [comment]
> Can you try this version and see if it works for you?
> 
> ```
> pnpm add https://pkg.pr.new/nuqs@694
> ```

@franky47 thanks for the prompt answer. Yup, that seems to work just fine.

**Comment by tiagoskaneta** [comment]
@franky47 working fine now, thanks for the release.

**Comment by rettgerst** [comment]
This seems to have reappeared in 2.3.2 (next 15.1.6).

In the meantime I have created this patch with [patch-package](https://www.npmjs.com/package/patch-package) to get myself by:

```diff
diff --git a/node_modules/nuqs/dist/chunk-S37JZELB.js b/node_modules/nuqs/dist/chunk-S37JZELB.js
index c915a96..e99aa69 100644
--- a/node_modules/nuqs/dist/chunk-S37JZELB.js
+++ b/node_modules/nuqs/dist/chunk-S37JZELB.js
@@ -1,6 +1,6 @@
 import { renderURL } from './chunk-QHW6KBHR.js';
 import { debug } from './chunk-3RCMAOX7.js';
-import { useRouter, useSearchParams } from 'next/navigation';
+import { useRouter, useSearchParams } from 'next/navigation.js';
 import { useOptimistic, useCallback, startTransition } from 'react';
 
 function useNuqsNextAppRouterAdapter() {
```

**Comment by franky47** [comment]
@rettgerst are you using the Next.js "router agnostic" adapter by any chance? If so, I'd love to hear more about your setup in #869.

If not, feel free to open a dedicated issue with your setup, thanks!

**Comment by rettgerst** [comment]
I am using the router-agnostic adapter. when I get the time I can provide more details in the linked issue, thanks.
