### ISSUE TITLE
`pnpm add nuqs` install both remix and next

### ISSUE THREAD

**Issue by nezouse** [47ng/nuqs#696]
## Context

What's your version of `nuqs`?

```
 "nuqs": "^2.0.0"
```

## Description
After adding nuqs to project with pnpm both next and remix (react-router) are installed. Usually you use only one of them.
The issues appears with fresh pnpm package without any modifications. 

## Reproduction
https://github.com/nezouse/nuqs-pnpm-repro

#### Steps to reproduce the behavior:
Just take a look at pnpm-lock.yaml or:
1. corepack enable
2. corepack pnpm install

To create a repro i did:
1. pnpm create
1. pnpm add nuqs

**Comment by franky47** [comment]
Thanks, I'm going to try and set up each framework as a `peerDependency` with `peerDependencyMeta.*.optional: true`, see if it helps. See #697 for tracking.

Also need to test with NPM, Yarn & Bun.
