### ISSUE TITLE
Serializer is returning an empty string on default search params in v2

### ISSUE THREAD

**Issue by blechatellier** [47ng/nuqs#715]
## Context

What's your version of `nuqs`?
`nuqs@2.0.4`

What framework are you using?
✅ Next.js (app router)

Which version of your framework are you using?
`next@15.0.1`

## Description

After upgrading to v2, the serializer returns an empty string when search params are using the default.

**Comment by franky47** [comment]
That's a consequence of the option `clearOnDefault` changing from `false` to `true` by default in v2.

It's true that this might be counter-intuitive for the serializer, if one wants to create a link that does hardcode the defaults in the URL.

Unfortunately for now, the serializer does not accept global options, like useQueryStates, but it should if we want to support urlKeys as well. In the mean time, the alternative would be to pass the `clearOnDefault: false` to each parser in the object when configuring the serializer:

```ts
const serialize = createSerializer({
  foo: parseAsString.withOptions({ clearOnDefault: false }),
  bar: parseAsInteger.withOptions({ clearOnDefault: false })
})
```

I'll see what I can do to add global options support this week.

**Comment by blechatellier** [comment]
Thanks @franky47 - setting clearOnDefault to false indeed fix the issue. Somehow my next implementation doesn't re-render unless the params are hardcoded.

**Comment by franky47** [comment]
Could you elaborate that last part? The useQueryState(s) hooks should follow the URL, and if a key isn't in the query string, return the default value if specified (or null otherwise).

**Comment by blechatellier** [comment]
I'm passing the `serialize` function directly to the `<Link href={serialize(...)} />` next component. When the params are matching the defaults, it sets the link to an empty string, preventing the page to re-render.

**Comment by kasperadk** [comment]
@blechatellier Thank you for posting this! I was struggling with the same problem.

**Comment by blechatellier** [comment]
@franky47 awesome, cleaner this way.

**Comment by blechatellier** [comment]
Thanks @franky47 🙏
