### ISSUE TITLE
NuqsTestingAdapter using Jest throwing "this package is ESM only."

### ISSUE THREAD

**Issue by GuilhermeMelow** [47ng/nuqs#727]
## Context

What's your version of `nuqs`?

```
-> 2.1.0
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```
-> 14.2.1
```

## Description

When I try to run tests and in this there are imports from `'nuqs/adapters/testing'` or any `'nuqs/*'`, jest display me the error message: 
`This package is ESM only.
      See https://github.com/47ng/nuqs/issues/691 for more details.`. I already reviewed the issue, but didn't find anything that could help me resolve this problem.

## Reproduction

https://codesandbox.io/p/live/7e72a9a1-a6f7-4696-83eb-5503e24fe781
Access the link, type `pnpm test` and press enter on terminal.

**Comment by franky47** [comment]
Yeah, getting Jest to work well with ESM packages is a bit of a sport, even in 2024.

I managed to make it work locally (but not in CodeSandbox) using these steps (following the [Jest ESM guide](https://jestjs.io/docs/ecmascript-modules)):
1. Add the following options to your jest.config.ts file:
```ts
extensionsToTreatAsEsm: [".ts", ".tsx"],
transform: {},
```
2. Start your test command with `NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" pnpm test`

**Comment by GuilhermeMelow** [comment]
Thanks for you help!
It's worked in parts, now this is throwing errors about global jest definition like in the print:
![image](https://github.com/user-attachments/assets/0d40d0ce-f42d-488e-86c2-69e69c69c2ea)

**Comment by franky47** [comment]
That's a Jest-specific issue now, not much to do with nuqs. Glad it helped you going forward!
