### ISSUE TITLE
nuqs 2 and jest compatibility issue

### ISSUE THREAD

**Issue by oyrad** [47ng/nuqs#741]
## Context

What's your version of `nuqs`?

2.1.1

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

14.2.3

## Description

Testing nuqs 2 using jest throws the following error:

```
Test suite failed to run

This package is ESM only.
See https://github.com/47ng/nuqs/issues/691 for more details.
```

The linked issue is of no help.

## Reproduction

1. Install `nuqs 2.x.x`
2. `import { NuqsTestingAdapter } from 'nuqs/adapters/testing'` in a test suite
3. Run any test
4. Get error

 -->

**Comment by franky47** [comment]
See #727 and #737 for solutions. Please try that and report back.

I'll update the error link to point to an aggregate ticket.
