### ISSUE TITLE
 Dependency Conflict Error During Vercel Deployment (Works Locally)

### ISSUE THREAD

**Issue by aeonzz** [47ng/nuqs#754]
## Context

What's your version of `nuqs`?

```
-> "nuqs": "^2.1.1"
```

What framework are you using?

- ✅ Next.js (app router)
- ❌ Next.js (pages router)
- ❌ React SPA (no router)
- ❌ Remix
- ❌ React Router
- ❌ Other (please specify)

Which version of your framework are you using?

```
-> "next": "15.0.3"
-> "react": "19.0.0-rc-66855b96-20241106"
-> "react-dom": "19.0.0-rc-66855b96-20241106"
```

## Description

My project is encountering a dependency conflict error during deployment on Vercel, specifically related to React versions. The project works fine locally, but fails during the Vercel build process. The error suggests a conflict between the pre-release version of React 19 we're using and the requirements of other packages, particularly `nuqs` and `@radix-ui` components.

## Reproduction

1. Push changes to the connected GitHub repository
2. Trigger a deployment on Vercel (automatically or manually)
3. Observe the build fail with the following error:

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: nuqs@2.1.1
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error   peer react@"^16.8 || ^17.0 || ^18.0 || ^19.0 || ^19.0.0-rc" from @radix-ui/react-arrow@1.1.0
npm error   node_modules/@radix-ui/react-arrow
npm error     @radix-ui/react-arrow@"1.1.0" from @radix-ui/react-popper@1.2.0
npm error     node_modules/@radix-ui/react-popper
npm error       @radix-ui/react-popper@"1.2.0" from @radix-ui/react-menu@2.1.2
npm error       node_modules/@radix-ui/react-menu
npm error         @radix-ui/react-menu@"2.1.2" from @radix-ui/react-dropdown-menu@2.1.2
npm error         node_modules/@radix-ui/react-dropdown-menu
npm error   38 more (@radix-ui/react-avatar, @radix-ui/react-collection, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@">= 18.2.0" from nuqs@2.1.1
npm error node_modules/nuqs
npm error   nuqs@"^2.1.1" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peer react@">= 18.2.0" from nuqs@2.1.1
npm error   node_modules/nuqs
npm error     nuqs@"^2.1.1" from the root project
```

Additional context:
- The project builds and runs without issues in the local development environment.
- We're using a pre-release version of React 19, which seems to be the root cause of the conflict.

Any insights or suggestions on resolving this deployment-specific dependency conflict would be greatly appreciated. Thank you!

**Comment by franky47** [comment]
What package manager are you using? If it's pnpm, do you have the `ENABLE_EXPERIMENTAL_COREPACK` environment variable set on Vercel?

**Comment by aeonzz** [comment]
Npm

**Comment by franky47** [comment]
The peer dependency range is satisfied, the only thing I see where things may go wrong is the extra space between the `>=` and the version number.

Could you try this version and see if it works better please?

```
npm i https://pkg.pr.new/nuqs@756
```

**Comment by aeonzz** [comment]
> The peer dependency range is satisfied, the only thing I see where things may go wrong is the extra space between the `>=` and the version number.
> 
> Not much hope, but could you try this version and see if it works better please?
> 
> ```
> npm i https://pkg.pr.new/nuqs@756
> ```

Thank you for your suggestion. I tried the command you provided, but unfortunately, the issue persists. Here's what happened:

- I attempted to install the package using the command you suggested:

```
 npm i https://pkg.pr.new/nuqs@756
```
- However, during the Vercel deployment, I still encountered an error:

```
npm error Could not resolve dependency:
npm error peer react@">=18.2.0" from nuqs@0.0.0-preview.598b0b0f997758b9fd5b3aba65c0032e6260f2be
npm error node_modules/nuqs
npm error   nuqs@"https://pkg.pr.new/nuqs@756" from the root project
```

- Additionally, when trying to install the package locally, I still need to use `--force` or `--legacy-peer-deps`. Here's the error I get without these flags:

```
npm error Could not resolve dependency:
npm error peer react@">= 18.2.0" from nuqs@2.1.1
npm error node_modules/nuqs
npm error   nuqs@"*" from the root project
```

**Comment by franky47** [comment]
Do you have a minimal reproducible repository I could deploy to Vercel to reproduce the issue on my end?

**Comment by aeonzz** [comment]
https://github.com/aeonzz/eqeon

**Comment by franky47** [comment]
Thanks, I managed to reproduce the issue on Vercel too, I'll let you know if I find some actionable solution.

**Comment by franky47** [comment]
Okay, so TIL that in SemVer, `>=18.2.0` does **not** include RC releases, so it was indeed not covering React 19 RC.

This should fix it:

```
npm i https://pkg.pr.new/nuqs@63566ad3d9254fdbf1288d3f66aeecc65d8f06d9
```

**Comment by aeonzz** [comment]
> Okay, so TIL that in SemVer, `>=18.2.0` does **not** include RC releases, so it was indeed not covering React 19 RC.
> 
> This should fix it:
> 
> ```
> npm i https://pkg.pr.new/nuqs@63566ad3d9254fdbf1288d3f66aeecc65d8f06d9
> ```

this works Thanks!!
