### ISSUE TITLE
Return value of `useQueryStates` does not immediately update after update in parsers

### ISSUE THREAD

**Issue by pdme** [47ng/nuqs#760]
## Context

What's your version of `nuqs`?
"nuqs": "^2.1.2"

What framework are you using?
NextJS

- ✅ Next.js (app router)

Which version of your framework are you using?
15.0.3

## Description
The return value of `useQueryStates` does not change if the parsers passed into it change.

## Reproduction

https://codesandbox.io/p/devbox/vkkl53

Example: Steps to reproduce the behavior:

1. Go to the codesandbox
2. Click on FLAG button
4. See that parsers change but return value not

 -->

**Comment by franky47** [comment]
What are you trying to achieve that requires switching the parser type for a given key at runtime?

**Comment by pdme** [comment]
I want to make the type of parser and its default value dependent on other parameters,. For example the user might trigger a setting that changes the nature of a certain query param, e.g. from single to multiple values, or having a different default value.

I can achieve this by sanitizing/parsing the values after the parsing by `useQueryStates`, but then I lose the default value behavior (back to `null`) and is frankly a bit cumbersome. Cleaner would be to be able to update the parsers at runtime...

**Comment by pdme** [comment]
You can set the default value dynamically, but only once. You cannot change the default value at runtime, based on external factors (see https://codesandbox.io/p/devbox/vkkl53)...

In any case, thanks for your answer, and a great library in general.

**Comment by franky47** [comment]
Ah, now this is indeed a bug with `useQueryStates`: changing the hook to useQueryState does follow a dynamic default value.

I'll take a look in #762, thanks!

**Comment by pdme** [comment]
great, thanks so much. I'll take a look myself in the meantime as well, see if I can find the culprit...

**Comment by franky47** [comment]
I think it has to do with the cache ref that's used for referential integrity, in useQueryState the default value is nullish-coalesced at the very end when returning the value, but in useQueryStates it's added to the cached state, and that isn't reactive to a change in the default value in the keyMap.

**Comment by franky47** [comment]
I've got a fix that passes tests, though I'll run some more to see if it didn't break referential stability as a side-effect.

Can you try the following please?

```
pnpm add https://pkg.pr.new/nuqs@762
```

Please note that it only handles dynamic defaults, and not changing parser types at runtime.

**Comment by pdme** [comment]
this seems to work! great job
