### ISSUE TITLE
withDefault not working on Next 15 server component

### ISSUE THREAD

**Issue by FezVrasta** [47ng/nuqs#773]
## Context

What's your version of `nuqs`? 

2.2.1

What framework are you using?

- ✅ Next.js (app router)
- ❌ Next.js (pages router)
- ❌ React SPA (no router)
- ❌ Remix
- ❌ React Router
- ❌ Other (please specify)

Which version of your framework are you using?

`next@npm:15.0.3`

## Description

I'm trying to upgrade my app from Next 14 to 15, but the following code starts failing:

```
const Page = async ({ searchParams }: Props) => {
 const { q: query, sport: sports } = createSearchParamsCache({
    q: parseAsString,
    sport: parseAsArrayOf<keyof typeof SPORTS>(
      parseAsStringEnum(Object.keys(SPORTS) as (keyof typeof SPORTS)[]),
    ).withDefault([]),
  }).parse(searchParams);
```

The `sports` variable ends up being `undefined` when no `sport` query parameters are set. On Next 14 it returns an empty array as expected.

## Reproduction

N/A

**Comment by franky47** [comment]
In Next.js 15, the `searchParams` page prop is a Promise, you'll need to `await` it (at either side of the .parse function, both work):

```ts
const Page = async ({ searchParams }: Props) => {
 const { q: query, sport: sports } = await createSearchParamsCache({
    q: parseAsString,
    sport: parseAsArrayOf<keyof typeof SPORTS>(
      parseAsStringEnum(Object.keys(SPORTS) as (keyof typeof SPORTS)[]),
    ).withDefault([]),
  }).parse(searchParams);
```

**Comment by FezVrasta** [comment]
Ah good to know, thanks!
