### ISSUE TITLE
useQueryState delayed triggering of suspense.

### ISSUE THREAD

**Issue by jericopulvera** [47ng/nuqs#775]
## Context

What's your version of `nuqs`?

```
"nuqs": "^2.0.4",
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: N/A
  react: 19.0.0-rc-fb9a90fa48-20240614
  react-dom: 19.0.0-rc-fb9a90fa48-20240614
  typescript: 5.6.3
Next.js Config:
```

## Description

setState has a delay in triggering the suspense loading. Lowering throttleMs seems to improve it, but it cannot go below 50 as per the documentation.

page
```tsx
        <Suspense
          fallback={<ProductListLoading />}
          key={JSON.stringify(searchParams)}
        >
          <div className="w-full">
            <ProductListServer />
          </div>
        </Suspense>
```

```ts
  const [page, setPage] = useQueryState(
    "page",
    searchParams.page.withOptions({
      startTransition,
      shallow: false,
      throttleMs: 50,
      scroll: true,
    }),
  ); 
  
  const onPaginate = (page: number) => {
    setPage(page)
  }; 
```

native router.replace works perfectly.
```ts
  const onPaginate = (page: number) => {
    const params = new URLSearchParams(searchParams);
    if (page) {
      params.set("page", page.toString());
    } else {
      params.delete("page");
    }
    router.replace(`${pathname}?${params.toString()}`);
  }; 
```

**Comment by franky47** [comment]
This is intentional: state updates are queued and throttled at 50ms minimum to avoid browsers rate-limiting history updates (that usually crash the app).

The internal state is optimistically updated instantly, then when it's time to update the URL, the startTransition function wraps around the router call that hits the server and updates the URL.

**Comment by jericopulvera** [comment]
Thanks. I figured that what I'm trying to do is not a library issue but an intended behavior of Suspense loading.

I was trying to figure out a way to trigger a suspense loading immediately on router change instead of showing a different loading state via startTransition loading.
