### ISSUE TITLE
useQueryState : TypeError: Cannot read properties of null (reading 'toString') 

### ISSUE THREAD

**Issue by Kamalito75** [47ng/nuqs#780]
## Context

What's your version of `nuqs`?

```
"nuqs": "^2.2.2"
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```
"next": "14.2.5"
```

## Description

I have a hook (useCreateSessionModal) to display a modal depending on the value of "create-session" from useQueryState :

```tsx
'use client'

import { parseAsBoolean, useQueryState } from "nuqs";

export const useCreateSessionModal = () => {
  const [isOpen, setIsOpen] = useQueryState(
    "create-session",
    parseAsBoolean.withDefault(false).withOptions({ clearOnDefault: true })
  );

  const open = () => setIsOpen(true);
  const close = () => setIsOpen(false);

  return {
    isOpen,
    open,
    close,
    setIsOpen,
  };
};
```

I have the following error : 
**TypeError: Cannot read properties of null (reading 'toString')**

![localhost-3000-11-22-2024_06_36_PM](https://github.com/user-attachments/assets/c71bf6c3-f3ff-415d-a9c6-a5527e1d154b)

**Comment by franky47** [comment]
Do you have more info of where the error is thrown from?

FYI, you don't need to specify clearOnDefault: true (it's the default value)

**Comment by Kamalito75** [comment]
I'm calling useCreateSessionModal from a client component (named client.tsx): 

```
"use client";

import { useCreateSessionModal } from "@/features/sessions/hooks/use-create-session-modal";

const AccountIdClient = () => {
  const { open: createSession } = useCreateSessionModal();

```

This client component is used in a page.tsx file : 
```
import React from 'react'
import AccountIdClient from './client'

export default function AccountPage() {
  return (
    <AccountIdClient />
  )
}
```

**Comment by Kamalito75** [comment]
The error is caused by the absence of the "create-session" URL parameter on the page that invokes the hook.
Should I check for the presence of create-session in the URL before calling useQueryState?

**Comment by franky47** [comment]
No, it takes care of that for you. When the search param is not present in the URL, the returned state is the default value.

Does the error pop up when rendering the component or is it when triggering an event?

Are you using the React Compiler by any chance?

**Comment by Kamalito75** [comment]
The error pops up when the component is rendered.
I'm building a minimal reproduction.

**Comment by Kamalito75** [comment]
Unfortunately, the issue is ongoing for me.
Here's the repro : https://codesandbox.io/p/github/Kamalito75/nextjs-nuqs/main?import=true . Please click on the Account link.

**Comment by Kamalito75** [comment]
Thanks for your help François. It solved my problem. Have a nice weekend.
