### ISSUE TITLE
Support for React Router 7

### ISSUE THREAD

**Issue by fobos531** [47ng/nuqs#782]
## Context

What's your version of `nuqs`?

```
2.2.2
```

What framework are you using?

- ✅ React Router

Which version of your framework are you using?

```
7.0.1
```

## Description

React router v7 was now released. See: https://reactrouter.com/ 

It seems `react-router-dom` is no longer a thing, everything now lives inside `react-router`. With that said, the existing adapter is no longer compatible with react router 7.

## Reproduction

1. Install react router 7
2. Attempt to use nuqs' react router adapter

**Comment by franky47** [comment]
I don't get it, their docs mention it's not a breaking change, but changing the package name is the breakiest of the changes..

I'd say the best way to handle this in nuqs is to have two adapters, one for v6 and one for v7:

- `nuqs/adapters/react-router`: v6 to avoid a breaking change in nuqs
- `nuqs/adapters/react-router/v7`: explicit support for v7
- `nuqs/adapters/react-router/v6`: alias of `nuqs/adapters/react-router` to help with transition

In the next major update of nuqs, we can then swap what `nuqs/adapters/react-router` point to.

**Comment by teukuamru** [comment]
> I don't get it, their docs mention it's not a breaking change, but changing the package name is the breakiest of the changes..
> 
> I'd say the best way to handle this in nuqs is to have two adapters, one for v6 and one for v7:
> 
> - `nuqs/adapters/react-router`: v6 to avoid a breaking change in nuqs
> - `nuqs/adapters/react-router/v7`: explicit support for v7
> - `nuqs/adapters/react-router/v6`: alias of `nuqs/adapters/react-router` to help with transition
> 
> In the next major update of nuqs, we can then swap what `nuqs/adapters/react-router` point to.

Any updates when will this be implemented?

**Comment by franky47** [comment]
Would you like to open a PR?

**Comment by teukuamru** [comment]
> Would you like to open a PR?

I have open a PR but this is my very first time opening a PR to an open source project. So feel free to add feedbacks cuz I know there will be a lot

**Comment by franky47** [comment]
Thanks and congrats for your first PR! ❤️

**Comment by omarkhatibco** [comment]
@franky47, could you please share when you could ship this?

**Comment by franky47** [comment]
@omarkhatibco hopefully this week, now that tests have been merged in #807, they confirmed a few issues:

- No support for `shallow: true` (the default) in react-router based adapters (v6, v7, and Remix)
- We could sneak in HashRouter support as noted in #810 (the implementation might be simple, the testing not so much)
