### ISSUE TITLE
App.tsx rerenders each time useQueryStates's setParams is called

### ISSUE THREAD

**Issue by didemkkaslan** [47ng/nuqs#803]
## Context

What's your version of `nuqs`?

```
"nuqs": "^2.2.3",
```

What framework are you using?

- ✅ Next.js (pages router)

Which version of your framework are you using?
```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:55 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 14.2.16 // An outdated version detected (latest is 15.1.0), upgrade is highly recommended!
  eslint-config-next: 15.0.2
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
 ⚠ An outdated version detected (latest is 15.1.0), upgrade is highly recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue
```

## Description
I'm using nuqs to store applied filters in the url as query params. As I'm typing the search param in the url is changing but I've realised the App.tsx file itself is rerendering each time. I'm not sure if its expected

## Reproduction

I'm using the basic usage example
My app.tsx
```tsx
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { NuqsAdapter } from 'nuqs/adapters/next/pages'


export default function App({ Component, pageProps }: AppProps) {
  console.log('hello app.tsx')
  return <NuqsAdapter><Component {...pageProps} /></NuqsAdapter>;
}

```
```tsx
export function Demo() {
  const [name, setName] = useQueryState('name')
  return (
    <>
      <input value={name || ''} onChange={e => setName(e.target.value)} />
      <button onClick={() => setName(null)}>Clear</button>
      <p>Hello, {name || 'anonymous visitor'}!</p>
    </>
  )
}
```
Each time url updates I see a new hello app.tsx in the console
 -->
 
 Is this expected?

**Comment by franky47** [comment]
Unfortunately, this is a behaviour from Next.js itself, you can see it without using nuqs, by calling the Next.js router directly:

https://github.com/franky47/nuqs-repro-803

**Comment by jonahallibone** [comment]
Is there no way to prevent this? Changing the input box on one of my pages causes my entire app to rerender, which in turn creates an incredibly laggy input box

**Comment by jonahallibone** [comment]
<img width="2560" alt="Image" src="https://github.com/user-attachments/assets/deddb012-cc65-48a0-8552-2fee2a427747" />


for reference

**Comment by franky47** [comment]
> Unfortunately, this is a behaviour from Next.js itself, you can see it without using nuqs, by calling the Next.js router directly:
> 
> [franky47/nuqs-repro-803](https://github.com/franky47/nuqs-repro-803?rgh-link-date=2024-12-12T08%3A43%3A58.000Z)

Yes, as you can see in the comment above, the repro that shows the _app.tsx component (and everything under it) re-renders does not use nuqs, it's only stock Next.js APIs.

Some possible mitigations options (which are general React recommendations, not related to Next.js):
- Memoising parts of the tree
- Leveraging useDeferredValue for non-critical rendering
