### ISSUE TITLE
Support for React 19 ?

### ISSUE THREAD

**Issue by issam-seghir** [47ng/nuqs#806]
## Context

What's your version of `nuqs`?

```
    "nuqs": "^2.2.3",
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```

Node.js v20.10.0

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32048
  Available CPU cores: 12
Binaries:
  Node: 20.10.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.3
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: 15.1.0
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

## Description

![image](https://github.com/user-attachments/assets/2d3656e0-7221-4f01-a252-ba724a639aaf)

**Comment by franky47** [comment]
Those are peer dependencies warning on `@radix-ui`, not nuqs, which works fine with React 19.

By the way, the React version in your package.json doesn't matter if you are using the app router, Next.js will use the vendored canary version they bring along.
