### ISSUE TITLE
Serializer breaks the right part of URLs containing multiple `?` characters

### ISSUE THREAD

**Issue by ealvarezk** [47ng/nuqs#812]
## Context

What's your version of `nuqs`?

```
2.2.3
```

What framework are you using?

- ✅ Next.js (app router)

Which version of your framework are you using?

```
Relevant Packages:
  next: 14.2.20 
  react: 18.3.1
  typescript: 5.5.4
```

## Description
When a serialize is executed with a string base parameter that have query string parameter with a string with "?", some of the string disappear 

## Reproduction
https://stackblitz.com/edit/vitejs-vite-wcnxdakb?file=src%2Fmain.ts

In this example you can see that we call serialize with a base parameter that have a query string with value1 that have a ? in the middle, and the result is `http://localhost:3000/?value1=value&prompt=value3` that deletes part of value1 and value 2.
```tsx
import { parseAsString, createSerializer } from 'nuqs';

const serialize = createSerializer({
  prompt: parseAsString,
});

const url = serialize('http://localhost:3000/?value1=value?With&value2=35435', {
  prompt: 'value3',
});
```

Reading you code I found the issue in line https://github.com/47ng/nuqs/blob/54067b39e91c42f30f45f38cb6b410960032d78b/packages/nuqs/src/serializer.ts#L84, where base is split but only use the first two elments of the returning array and get rid of the remaining

**Comment by franky47** [comment]
Thanks for the report, sounds like it should be an easy fix, would you like to open a PR?
